# Default values for eck-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

elasticsearch: 
  version: 8.4.0
  master:
    replicas: 1
    volume:
      storageClass: gp2
      size: 10Gi
  data:
    replicas: 3
    volume:
      storageClass: gp2
      size: 100Gi
  service:
    name: elasticsearch
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  httpService:
    name: elasticsearch-es-http
    port: 9200
    scheme: http
    sslVerify: false

kibana:
  version: 8.4.0
  service:
    name: kibana
    type: NodePort
    port: 5601
    targetPort: 5601
  apiService: 
    name: kibana-kb-http
    port: 5601
  secret:
      name: elasticsearch-es-elastic-user
      user: elastic
      pwd: 

fluentd:
  service:
    name: fluentd
  config:
    name: fluentdconfig