apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eck-stack.fullname" . }}-kibana-import
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: kibana-data
        configMap:
            name: kibana-data
            defaultMode: 0777
      containers:
      - name: kibanax-import
        image: couchbase/centos7-systemd
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_URL
          value: {{ include "eck-stack.fullname" . }}-{{ .Values.kibana.apiService.name }}
        - name: KIBANA_PORT
          value: "{{ .Values.kibana.apiService.port }}"
        - name: ELASTIC_USER
          value: {{ .Values.kibana.secret.user}}
        - name: ELASTIC_PWD
          valueFrom:
            secretKeyRef:
              name: {{ include "eck-stack.fullname" . }}-{{ .Values.kibana.secret.name }}
              key: elastic
        command: ["/bin/sh","/kibana/curl-script.sh"]
        volumeMounts:
        - name: kibana-data
          mountPath: /kibana/