# Default values for efk-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

elasticsearch: 
  version: 8.5.0
  master:
    replicas: 1
    volume:
      storageClass: local-path
      size: 10Gi
  data:
    replicas: 1
    volume:
      storageClass: local-path
      size: 10Gi
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
  http:
    tls:
      disabled: false
  auth:
    disabled: true

kibana:
  ##need to be the same as elasticsearch so if commented it will be the elastic version
  # version: 8.5.2
  service:
    type: NodePort
    port: 5601
    targetPort: 5601
  http:
    tls:
      disabled: true
  ## the default user is elastic
  ## the default password is 1234
  password:
  ## insert here an exported dashboard json file content for auto import 
  dashboard: |
    {"attributes":{"fieldAttrs":"{}","fields":"[]","runtimeFieldMap":"{}","timeFieldName":"@timestamp","title":"logstash-*","typeMeta":"{}"},"coreMigrationVersion":"8.2.2","id":"683a2d10-08fb-11ed-8cae-2d280a9cf5cc","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2022-07-21T13:45:39.686Z","version":"WzEwNDUsMV0="}
      

fluentd:
  config:
    name: fluentdconfig
